---
- name: 'Install required packages'
  become: yes
  apt:
    name: ['libvirt-daemon-system', 'libvirt-clients', 'virt-manager']
    state: present

- include_role:
    name: user
  vars:
    user_groups: ['libvirt']

- name: 'Start libvirtd service'
  become: yes
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: 'Autostart default network'
  become: yes
  shell: 'virsh net-autostart default'
